In [1]:
import pandas as pd
import numpy as np

# importing the dataset

In [2]:
df_nsso=pd.read_csv("D:/4. NSSO68 data set.csv")

C:\Users\Indrani Sen\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
df_nsso.shape

(101662, 384)

In [5]:
df_nsso.columns

Index(['Unnamed: 0', 'grp', 'Round_Centre', 'FSU_number', 'Round',
       'Schedule_Number', 'Sample', 'Sector', 'state', 'State_Region',
       ...
       'pickle_v', 'sauce_jam_v', 'Othrprocessed_v', 'Beveragestotal_v',
       'foodtotal_v', 'foodtotal_q', 'state_1', 'Region', 'fruits_df_tt_v',
       'fv_tot'],
      dtype='object', length=384)

In [4]:
df_nsso.head()

Unnamed: 0                                 grp  Round_Centre  FSU_number  \
0           1  40999999999999992652495293775872.0             1       41000   
1           2  40999999999999992652495293775872.0             1       41000   
2           3  40999999999999992652495293775872.0             1       41000   
3           4  40999999999999992652495293775872.0             1       41000   
4           5  40999999999999992652495293775872.0             1       41000   

   Round  Schedule_Number  Sample  Sector  state  State_Region  ...  pickle_v  \
0     68               10       1       2     24           242  ...       0.0   
1     68               10       1       2     24           242  ...       0.0   
2     68               10       1       2     24           242  ...       0.0   
3     68               10       1       2     24           242  ...       0.0   
4     68               10       1       2     24           242  ...       0.0   

   sauce_jam_v  Othrprocessed_v  Beveragestotal_v  foodtotal_v  foodtotal_q  \
0          0.0              0.0          0.000000  1141.492400    30.942394   
1          0.0              0.0         17.500000  1244.553500    29.286153   
2          0.0              0.0          0.000000  1050.315400    31.527046   
3          0.0              0.0         33.333333  1142.591667    27.834607   
4          0.0              0.0         75.000000   945.249500    27.600713   

   state_1  Region  fruits_df_tt_v  fv_tot  
0      GUJ       2       12.000000  154.18  
1      GUJ       2      333.000000  484.95  
2      GUJ       2       35.000000  214.84  
3      GUJ       2      168.333333  302.30  
4      GUJ       2       15.000000  148.00  

[5 rows x 384 columns]

In [6]:
df_nsso=df_nsso.drop("Unnamed: 0",axis=1)

In [7]:
df_nsso.head()

grp  Round_Centre  FSU_number  Round  \
0  40999999999999992652495293775872.0             1       41000     68   
1  40999999999999992652495293775872.0             1       41000     68   
2  40999999999999992652495293775872.0             1       41000     68   
3  40999999999999992652495293775872.0             1       41000     68   
4  40999999999999992652495293775872.0             1       41000     68   

   Schedule_Number  Sample  Sector  state  State_Region  District  ...  \
0               10       1       2     24           242         7  ...   
1               10       1       2     24           242         7  ...   
2               10       1       2     24           242         7  ...   
3               10       1       2     24           242         7  ...   
4               10       1       2     24           242         7  ...   

   pickle_v  sauce_jam_v  Othrprocessed_v  Beveragestotal_v  foodtotal_v  \
0       0.0          0.0              0.0          0.000000  1141.492400   
1       0.0          0.0              0.0         17.500000  1244.553500   
2       0.0          0.0              0.0          0.000000  1050.315400   
3       0.0          0.0              0.0         33.333333  1142.591667   
4       0.0          0.0              0.0         75.000000   945.249500   

   foodtotal_q  state_1  Region  fruits_df_tt_v  fv_tot  
0    30.942394      GUJ       2       12.000000  154.18  
1    29.286153      GUJ       2      333.000000  484.95  
2    31.527046      GUJ       2       35.000000  214.84  
3    27.834607      GUJ       2      168.333333  302.30  
4    27.600713      GUJ       2       15.000000  148.00  

[5 rows x 383 columns]

In [8]:
df_nsso.columns

Index(['grp', 'Round_Centre', 'FSU_number', 'Round', 'Schedule_Number',
       'Sample', 'Sector', 'state', 'State_Region', 'District',
       ...
       'pickle_v', 'sauce_jam_v', 'Othrprocessed_v', 'Beveragestotal_v',
       'foodtotal_v', 'foodtotal_q', 'state_1', 'Region', 'fruits_df_tt_v',
       'fv_tot'],
      dtype='object', length=383)

In [9]:
df_nsso.columns.get_loc("MPCE_MRP")

50

In [10]:
df_nsso.dtypes

grp                 object
Round_Centre         int64
FSU_number           int64
Round                int64
Schedule_Number      int64
                    ...   
foodtotal_q        float64
state_1             object
Region               int64
fruits_df_tt_v     float64
fv_tot             float64
Length: 383, dtype: object

In [ ]:
#target variable MPCE	Monthly Per-capita Consumer Expenditure
#In India, there were two main ways of collecting data: Uniform Reference Period (URP) and Mixed Reference Period (MRP). 
#Up until 1993-94, the poverty line was based on URP data. 
#This involved asking people about their consumption expenditure across a 30-day recall period. 
#Since 1999-2000, however, data are being collected according to MRP. 
#Under this method, data on five less-frequently used items are collected over a one-year period, 
#while sticking to the 30-day recall for the rest of the items.

In [14]:
i=df_nsso.dtypes[df_nsso.dtypes=="object"].index
i

Index(['grp', 'state_1'], dtype='object')

In [15]:
df_nsso=df_nsso.drop(i,axis=1)

In [16]:
df_nsso.dtypes[df_nsso.dtypes=="object"].index

Index([], dtype='object')

In [ ]:
#missing values

In [17]:
df_nsso.isna().sum()

Round_Centre       0
FSU_number         0
Round              0
Schedule_Number    0
Sample             0
                  ..
foodtotal_v        0
foodtotal_q        0
Region             0
fruits_df_tt_v     0
fv_tot             0
Length: 381, dtype: int64

In [18]:
df_missing=df_nsso.isna().sum()


In [19]:
df_missing[df_missing>0]

FOD_Sub_Region                          8
NIC_2008                             7511
NCO_2004                             7487
HH_type                                27
Religion                                3
Social_Group                           14
Whether_owns_any_land                  10
Type_of_land_owned                  13905
Land_Owned                          14415
Land_Leased_in                      83852
Otherwise_possessed                 97383
Land_Leased_out                     96800
Land_Total_possessed                  439
During_July_June_Cultivated         59682
During_July_June_Irrigated          77148
land_tt                               439
Cooking_code                            5
Lighting_code                           8
Dwelling_unit_code                      7
Regular_salary_earner                  12
Perform_Ceremony                       64
Meals_seved_to_non_hhld_members     11385
Possess_ration_card                    13
Type_of_ration_card               

In [20]:
df_missing=df_missing[df_missing>0]

In [21]:
df_missing.index

Index(['FOD_Sub_Region', 'NIC_2008', 'NCO_2004', 'HH_type', 'Religion',
       'Social_Group', 'Whether_owns_any_land', 'Type_of_land_owned',
       'Land_Owned', 'Land_Leased_in', 'Otherwise_possessed',
       'Land_Leased_out', 'Land_Total_possessed',
       'During_July_June_Cultivated', 'During_July_June_Irrigated', 'land_tt',
       'Cooking_code', 'Lighting_code', 'Dwelling_unit_code',
       'Regular_salary_earner', 'Perform_Ceremony',
       'Meals_seved_to_non_hhld_members', 'Possess_ration_card',
       'Type_of_ration_card', 'Marital_Status', 'Education',
       'Days_Stayed_away', 'No_of_Meals_per_day', 'Meals_School',
       'Meals_Employer', 'Meals_Others', 'Meals_Payment', 'Meals_At_Home',
       'Source_Code', 'soyabean_q', 'soyabean_v'],
      dtype='object')

In [22]:
df_nsso=df_nsso.drop(df_missing.index,axis=1)

In [23]:
df_nsso.corr()

Round_Centre  FSU_number  Round  Schedule_Number  Sample  \
Round_Centre              NaN         NaN    NaN              NaN     NaN   
FSU_number                NaN    1.000000    NaN              NaN     NaN   
Round                     NaN         NaN    NaN              NaN     NaN   
Schedule_Number           NaN         NaN    NaN              NaN     NaN   
Sample                    NaN         NaN    NaN              NaN     NaN   
...                       ...         ...    ...              ...     ...   
foodtotal_v               NaN   -0.149950    NaN              NaN     NaN   
foodtotal_q               NaN    0.067969    NaN              NaN     NaN   
Region                    NaN    0.016304    NaN              NaN     NaN   
fruits_df_tt_v            NaN   -0.174930    NaN              NaN     NaN   
fv_tot                    NaN   -0.199785    NaN              NaN     NaN   

                   Sector     state  State_Region  District  Stratum_Number  \
Round_Centre          NaN       NaN           NaN       NaN             NaN   
FSU_number      -0.983359 -0.177290     -0.176650  0.054673       -0.043205   
Round                 NaN       NaN           NaN       NaN             NaN   
Schedule_Number       NaN       NaN           NaN       NaN             NaN   
Sample                NaN       NaN           NaN       NaN             NaN   
...                   ...       ...           ...       ...             ...   
foodtotal_v      0.169540 -0.087064     -0.088216 -0.118092       -0.068891   
foodtotal_q     -0.028308 -0.269094     -0.268714  0.001541       -0.006701   
Region          -0.024192  0.164806      0.178116  0.259461        0.189453   
fruits_df_tt_v   0.179982  0.107079      0.106632  0.005735        0.039583   
fv_tot           0.199041  0.048699      0.047313 -0.053705       -0.005308   

                 ...  preparedsweet_v  pickle_v  sauce_jam_v  Othrprocessed_v  \
Round_Centre     ...              NaN       NaN          NaN              NaN   
FSU_number       ...        -0.090445 -0.078351    -0.101913        -0.004851   
Round            ...              NaN       NaN          NaN              NaN   
Schedule_Number  ...              NaN       NaN          NaN              NaN   
Sample           ...              NaN       NaN          NaN              NaN   
...              ...              ...       ...          ...              ...   
foodtotal_v      ...         0.361161  0.196422     0.196034         0.228803   
foodtotal_q      ...         0.234958  0.117884     0.096306         0.002165   
Region           ...        -0.012871 -0.041888    -0.033557        -0.007688   
fruits_df_tt_v   ...         0.269367  0.167347     0.224215         0.015435   
fv_tot           ...         0.285971  0.210320     0.210049         0.016633   

                 Beveragestotal_v  foodtotal_v  foodtotal_q    Region  \
Round_Centre                  NaN          NaN          NaN       NaN   
FSU_number              -0.064395    -0.149950     0.067969  0.016304   
Round                         NaN          NaN          NaN       NaN   
Schedule_Number               NaN          NaN          NaN       NaN   
Sample                        NaN          NaN          NaN       NaN   
...                           ...          ...          ...       ...   
foodtotal_v              0.389706     1.000000     0.787934 -0.099036   
foodtotal_q              0.103886     0.787934     1.000000 -0.018409   
Region                  -0.030658    -0.099036    -0.018409  1.000000   
fruits_df_tt_v           0.154347     0.555499     0.352738 -0.014251   
fv_tot                   0.171546     0.718523     0.556096 -0.092825   

                 fruits_df_tt_v    fv_tot  
Round_Centre                NaN       NaN  
FSU_number            -0.174930 -0.199785  
Round                       NaN       NaN  
Schedule_Number             NaN       NaN  
Sample                      NaN       NaN  
...                         .

In [32]:
df_corr=df_nsso.corr()["MPCE_MRP"]>.3

In [33]:
df_col=df_corr[df_corr==True].index
df_col

Index(['MPCE_URP', 'MPCE_MRP', 'milk_q', 'milkprott_q', 'edibletotal_q',
       'bananano_q', 'apple_q', 'fruitt_total', 'spicetot_q', 'spicestotal_q',
       'pulsestot_v', 'pulsestt_v', 'milk_v', 'Milktotal_v', 'milkprott_v',
       'edibletotal_v', 'emftt_v', 'onion_v', 'tamato_v', 'vegtt_v',
       'bananano_v', 'apple_v', 'dftt_v', 'sugartotal_v', 'spicetot_v',
       'spicestotal_v', 'Biscuits_v', 'foodtotal_v', 'foodtotal_q',
       'fruits_df_tt_v', 'fv_tot'],
      dtype='object')

In [34]:
x=df_nsso.loc[:,df_col]


In [36]:
x.shape

(101662, 31)

In [37]:
#removing target variable
x=x.drop("MPCE_MRP",axis=1)
x.head()
x.shape

(101662, 30)

In [38]:
x_missing=x.isna().sum()

x_missing[x_missing==True]


Series([], dtype: int64)

In [39]:
df_nsso.columns.get_loc("MPCE_MRP")

25

In [40]:
y=df_nsso.iloc[:,25]
y.head()

0    3662.65
1    5624.51
2    3657.18
3    3260.37
4    2627.54
Name: MPCE_MRP, dtype: float64

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
x_tr,x_test,y_tr,y_test=train_test_split(x,y,test_size=.2)

In [42]:
lm_model=LinearRegression().fit(x_tr,y_tr)

In [43]:
p=lm_model.predict(x_test)

In [44]:
r2_score(y_test,p)

0.565860680797452

# Normalisation of data using standard scaler

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaled_model=StandardScaler()

In [47]:
x_scaled=scaled_model.fit_transform(x)


In [48]:
x_scaled

array([[ 0.29812753,  0.68726749,  0.6643524 , ...,  0.65401331,
        -0.34229662,  0.50073912],
       [ 1.32242104,  0.24907672,  0.27159834, ...,  0.48778918,
         5.56743182,  4.23378095],
       [ 0.33535987,  0.16143857,  0.24652893, ...,  0.7126903 ,
         0.08114187,  1.18534268],
       ...,
       [-0.32990309,  0.61214907,  0.58986044, ...,  0.13792181,
        -0.56322104, -0.87494932],
       [-0.28617768,  1.2130964 ,  1.18579608, ...,  0.58152928,
        -0.56322104, -0.79691529],
       [-0.32365491,  0.61214907,  0.58986044, ...,  0.17376834,
        -0.56322104, -0.7911111 ]])

In [49]:
x_scaled.shape

(101662, 30)

In [50]:
np.any(np.isnan(x_scaled))

False

In [51]:
np.any(np.isfinite(x_scaled))

True

In [52]:
x_scaled = np.nan_to_num(x_scaled)

In [53]:
x_scaled.shape

(101662, 30)

# performing PCA

In [54]:
from sklearn.decomposition import PCA
pca=PCA(n_components = 0.95)

In [ ]:
#calculating covariance matrix

In [ ]:
x

In [55]:
x=x_scaled


In [56]:
x

array([[ 0.29812753,  0.68726749,  0.6643524 , ...,  0.65401331,
        -0.34229662,  0.50073912],
       [ 1.32242104,  0.24907672,  0.27159834, ...,  0.48778918,
         5.56743182,  4.23378095],
       [ 0.33535987,  0.16143857,  0.24652893, ...,  0.7126903 ,
         0.08114187,  1.18534268],
       ...,
       [-0.32990309,  0.61214907,  0.58986044, ...,  0.13792181,
        -0.56322104, -0.87494932],
       [-0.28617768,  1.2130964 ,  1.18579608, ...,  0.58152928,
        -0.56322104, -0.79691529],
       [-0.32365491,  0.61214907,  0.58986044, ...,  0.17376834,
        -0.56322104, -0.7911111 ]])

In [57]:
x.shape

(101662, 30)

In [62]:
x1=x-np.mean(x,axis=0)
x1

array([[ 0.29812753,  0.68726749,  0.6643524 , ...,  0.65401331,
        -0.34229662,  0.50073912],
       [ 1.32242104,  0.24907672,  0.27159834, ...,  0.48778918,
         5.56743182,  4.23378095],
       [ 0.33535987,  0.16143857,  0.24652893, ...,  0.7126903 ,
         0.08114187,  1.18534268],
       ...,
       [-0.32990309,  0.61214907,  0.58986044, ...,  0.13792181,
        -0.56322104, -0.87494932],
       [-0.28617768,  1.2130964 ,  1.18579608, ...,  0.58152928,
        -0.56322104, -0.79691529],
       [-0.32365491,  0.61214907,  0.58986044, ...,  0.17376834,
        -0.56322104, -0.7911111 ]])

In [65]:
cov_matrix = np.dot(x.T, x) / x.shape[0]
cov_matrix

array([[ 1.        ,  0.17347082,  0.17915311,  0.16897859,  0.19207765,
         0.19250031,  0.26479714,  0.1960377 ,  0.19206244,  0.18271764,
         0.18271764,  0.19453592,  0.22287249,  0.22219512,  0.18612048,
         0.1861996 ,  0.17659906,  0.16478809,  0.19373738,  0.2117967 ,
         0.21403055,  0.16520506,  0.17615837,  0.22255855,  0.21616589,
         0.15593969,  0.31560134,  0.19657759,  0.27145099,  0.28595461],
       [ 0.17347082,  1.        ,  0.99851482,  0.29511031,  0.1534594 ,
         0.27653781,  0.2857595 ,  0.18777648,  0.19218955,  0.29161606,
         0.29161606,  0.95321303,  0.90731132,  0.91010455,  0.28050735,
        -0.06069733,  0.23944036,  0.24515985,  0.18278401,  0.19340609,
         0.24648217,  0.22401215,  0.44614384,  0.25391882,  0.26273137,
         0.11249616,  0.59508268,  0.72793225,  0.3182997 ,  0.30791477],
       [ 0.17915311,  0.99851482,  1.        ,  0.30564966,  0.16061786,
         0.28327166,  0.29529465,  0.1961324 ,  0

In [66]:
X=x_scaled
X =X- np.mean(X, axis=0)
cov_matrix = np.dot(X.T, X) / X.shape[0]

In [67]:
cov_matrix

array([[ 1.        ,  0.17347082,  0.17915311,  0.16897859,  0.19207765,
         0.19250031,  0.26479714,  0.1960377 ,  0.19206244,  0.18271764,
         0.18271764,  0.19453592,  0.22287249,  0.22219512,  0.18612048,
         0.1861996 ,  0.17659906,  0.16478809,  0.19373738,  0.2117967 ,
         0.21403055,  0.16520506,  0.17615837,  0.22255855,  0.21616589,
         0.15593969,  0.31560134,  0.19657759,  0.27145099,  0.28595461],
       [ 0.17347082,  1.        ,  0.99851482,  0.29511031,  0.1534594 ,
         0.27653781,  0.2857595 ,  0.18777648,  0.19218955,  0.29161606,
         0.29161606,  0.95321303,  0.90731132,  0.91010455,  0.28050735,
        -0.06069733,  0.23944036,  0.24515985,  0.18278401,  0.19340609,
         0.24648217,  0.22401215,  0.44614384,  0.25391882,  0.26273137,
         0.11249616,  0.59508268,  0.72793225,  0.3182997 ,  0.30791477],
       [ 0.17915311,  0.99851482,  1.        ,  0.30564966,  0.16061786,
         0.28327166,  0.29529465,  0.1961324 ,  0

In [68]:
np.cov(X.T)

array([[ 1.00000984,  0.17347253,  0.17915488,  0.16898025,  0.19207954,
         0.1925022 ,  0.26479974,  0.19603963,  0.19206433,  0.18271943,
         0.18271943,  0.19453783,  0.22287468,  0.22219731,  0.18612231,
         0.18620143,  0.1766008 ,  0.16478972,  0.19373928,  0.21179879,
         0.21403265,  0.16520668,  0.1761601 ,  0.22256074,  0.21616802,
         0.15594122,  0.31560444,  0.19657952,  0.27145366,  0.28595742],
       [ 0.17347253,  1.00000984,  0.99852464,  0.29511321,  0.15346091,
         0.27654053,  0.28576231,  0.18777833,  0.19219144,  0.29161893,
         0.29161893,  0.95322241,  0.90732024,  0.91011351,  0.28051011,
        -0.06069792,  0.23944272,  0.24516226,  0.18278581,  0.19340799,
         0.24648459,  0.22401435,  0.44614823,  0.25392132,  0.26273395,
         0.11249727,  0.59508854,  0.72793941,  0.31830283,  0.3079178 ],
       [ 0.17915488,  0.99852464,  1.00000984,  0.30565267,  0.16061944,
         0.28327445,  0.29529756,  0.19613433,  0

In [69]:
x_pca = pca.fit_transform(x_scaled)
x_pca.shape

(101662, 14)

In [77]:
pca.explained_variance_ratio_

array([0.40007658, 0.12684011, 0.09379072, 0.05502317, 0.04635376,
       0.04392408, 0.03530601, 0.03085276, 0.02787466, 0.02756175,
       0.02355136, 0.01656072, 0.01535452, 0.01440669])

In [71]:
y.shape

(101662,)

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
from sklearn.linear_model import LinearRegression

In [80]:
x_tr,x_test,y_tr,y_test=train_test_split(x_pca,y,test_size=.2)

In [81]:
x_tr.shape

(81329, 14)

In [82]:
x_test.shape

(20333, 14)

In [83]:
model_lm_pca=LinearRegression().fit(x_tr,y_tr)

In [84]:
explained_variance=pca.explained_variance_ratio_

In [85]:
explained_variance

array([0.40007658, 0.12684011, 0.09379072, 0.05502317, 0.04635376,
       0.04392408, 0.03530601, 0.03085276, 0.02787466, 0.02756175,
       0.02355136, 0.01656072, 0.01535452, 0.01440669])

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
model_lm=LinearRegression().fit(x_tr,y_tr)

In [88]:
y_tr.shape

(81329,)

In [89]:
x_tr.shape

(81329, 14)

In [90]:
x_test.shape

(20333, 14)

In [91]:
p=model_lm.predict(x_test)

In [92]:
from sklearn.metrics import r2_score
r2_score(y_test,p)

0.520303320939954