In [1]:
import pandas as pd

# import the dataset

In [2]:
df_admit=pd.read_csv("c:/csv/admission_predict.csv")

In [3]:
df1=df_admit.head(5)

# Extracting the first 5 records

In [4]:
df1

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

# Selecting the GRE Score and the Chance of admit column

In [5]:
df1=df1.iloc[:,[1,8]]

In [6]:
df1

GRE Score  Chance of Admit 
0        337              0.92
1        324              0.76
2        316              0.72
3        322              0.80
4        314              0.65

# setting GRE score as X vector

In [7]:
df1_x=df1.iloc[:,[0]]

In [8]:
df1_x

GRE Score
0        337
1        324
2        316
3        322
4        314

# converting object to numeric column

In [9]:
x=df1_x.iloc[:,0]

In [10]:
x=pd.to_numeric(x)

# setting Chance of admit as Y vector

In [11]:
df1_y=df1.iloc[:,[1]]

In [12]:
df1_y

Chance of Admit 
0              0.92
1              0.76
2              0.72
3              0.80
4              0.65

# converting object to numeric column

In [13]:
y=df1_y.iloc[:,0]

In [14]:
import numpy as np

# calculating the mean of x and y vectors

In [15]:
df1_x_mean=np.mean(df1_x)

In [16]:
df1_x_mean

GRE Score    322.6
dtype: float64

In [17]:
df1_y_mean=np.mean(df1_y)

In [18]:
df1_y_mean

Chance of Admit     0.77
dtype: float64

# calculating the deviation 

In [19]:
deviation_x=[]
for i in x:
    deviation_x.append(i-df1_x_mean)
    

In [20]:
deviation_x

[GRE Score    14.4
 dtype: float64,
 GRE Score    1.4
 dtype: float64,
 GRE Score   -6.6
 dtype: float64,
 GRE Score   -0.6
 dtype: float64,
 GRE Score   -8.6
 dtype: float64]

In [21]:
deviation_y=[]
for i in y:
    deviation_y.append(i-df1_y_mean)
    
deviation_y


[Chance of Admit     0.15
 dtype: float64,
 Chance of Admit    -0.01
 dtype: float64,
 Chance of Admit    -0.05
 dtype: float64,
 Chance of Admit     0.03
 dtype: float64,
 Chance of Admit    -0.12
 dtype: float64]

# calculating the product of deviation

In [22]:
product_deviation=np.array(deviation_x)*np.array(deviation_y)
product_deviation

array([[ 2.16 ],
       [-0.014],
       [ 0.33 ],
       [-0.018],
       [ 1.032]])

In [23]:
Sum_product_deviation=np.sum(product_deviation)
Sum_product_deviation

3.4900000000000007

# calculating the square of deviation of x and y

In [24]:
Sq_x_deviation=np.array(deviation_x)**2
Sq_x_deviation

array([[207.36],
       [  1.96],
       [ 43.56],
       [  0.36],
       [ 73.96]])

In [25]:
Sum_Sq_x_deviation=np.sum(Sq_x_deviation)
Sum_Sq_x_deviation

327.19999999999993

# calculating the regression coefficient, the slope of regression line

In [26]:
Regression_coefficient=Sum_product_deviation/Sum_Sq_x_deviation
Regression_coefficient

0.01066625916870416

# calculating the intercept

In [27]:
intercept=np.float(df1_y_mean)-(Regression_coefficient*np.float(df1_x_mean))
intercept

-2.6709352078239625

In [28]:
test_data=[320,325]

# calculating the predicted value of y from test data

In [29]:
predicted_y1=Regression_coefficient*test_data[0]+intercept
predicted_y1

0.7422677261613688

In [30]:
predicted_y2=Regression_coefficient*test_data[1]+intercept
predicted_y2

0.7955990220048896

# Implementing linear regression with SKLearn library

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
model1=LinearRegression()

In [33]:
#training the model with X as feature  and Y as target

In [34]:
model1=model1.fit(df1_x,df1_y)

In [35]:
model1

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# printing the regression coefficient or the slope of the regression line

In [36]:
print(model1.coef_)

[[0.01066626]]


# printing the intercept

In [37]:
print(model1.intercept_)

[-2.67093521]


# creating the test dataset

In [39]:
x_test=pd.DataFrame({"GRE Score":[320,325]})

# Predicting the value of Y (Chance of admit)

In [41]:
p=model1.predict(x_test)

In [42]:
p

array([[0.74226773],
       [0.79559902]])

# Calculating R2_score

In [43]:
from sklearn.metrics import r2_score

# The target variable of the test dataset is unknown so we need to use the training dataset

In [45]:
p_tr=model1.predict(df1_x)

In [46]:
r2_score(df1_y,p_tr)

0.9214169430390473