In [1]:
import pandas as pd

In [2]:
df_boston=pd.read_csv("d:/csv-ml/boston_dataset.csv")

In [3]:
df_boston.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
df_boston=df_boston.drop("Unnamed: 0",axis=1)

In [7]:
df_boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [9]:
x=df_boston.iloc[:,0:13]
x.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [10]:
y=df_boston["medv"]
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

In [ ]:
x.head()

In [ ]:
y.head()

In [11]:
x_tr,x_test,y_tr,y_test=train_test_split(x,y,test_size=.2)

In [12]:
model1=LinearRegression()

In [13]:
model1.fit(x_tr,y_tr)

LinearRegression()

In [14]:
p=model1.predict(x_test)

In [15]:
p

array([31.35775052, 11.33949827, 10.73030951, 14.20032518, 12.99592161,
       21.7560658 , 22.17457596, 22.91124616, 39.65045365, 34.87521961,
       27.66942039, 13.47090085, 12.01794462,  3.16456987, 29.05561338,
       25.03707691, 31.9782309 , 34.90412822, 29.15757414, 25.15731191,
       30.17846009, 20.21776593, 13.7758394 , 15.56715427, 21.12601573,
       13.05827131, 35.97018974, 18.49190616, 15.58043183, 24.11434382,
       36.04049736, 17.19517251, 17.15527548, 33.40349803, 26.76914956,
       21.38064544, 22.27232786, 26.66867802, 19.83556774, 29.73875589,
       23.85733977, 20.70376559, 19.60477748, 34.96338575, 22.58670771,
        3.41278324, 34.62369111, 22.80358202, 15.16337821, 19.33356285,
       27.55096665, 31.83433948, 27.7494629 , 35.83424724, 16.26033588,
       17.68242469, 37.37614934, 16.41930026, 33.38213047, 12.46345181,
       28.60320968, 17.85716859, 29.50080738, 36.82727746, 18.12409313,
       34.55257242, 32.94541367, 11.28231178, 27.58780333, 21.71

In [16]:
p.shape

(102,)

In [17]:
from scipy.stats import pearsonr

In [18]:
len(y_test)

102

In [19]:
len(p)

102

In [20]:
type(y_test)

pandas.core.series.Series

In [21]:
type(p)

numpy.ndarray

In [22]:
y_test

305    28.4
143    15.6
8      16.5
149    15.4
435    13.4
       ... 
162    50.0
178    29.9
28     18.4
361    19.9
505    11.9
Name: medv, Length: 102, dtype: float64

In [25]:
p

array([31.35775052, 11.33949827, 10.73030951, 14.20032518, 12.99592161,
       21.7560658 , 22.17457596, 22.91124616, 39.65045365, 34.87521961,
       27.66942039, 13.47090085, 12.01794462,  3.16456987, 29.05561338,
       25.03707691, 31.9782309 , 34.90412822, 29.15757414, 25.15731191,
       30.17846009, 20.21776593, 13.7758394 , 15.56715427, 21.12601573,
       13.05827131, 35.97018974, 18.49190616, 15.58043183, 24.11434382,
       36.04049736, 17.19517251, 17.15527548, 33.40349803, 26.76914956,
       21.38064544, 22.27232786, 26.66867802, 19.83556774, 29.73875589,
       23.85733977, 20.70376559, 19.60477748, 34.96338575, 22.58670771,
        3.41278324, 34.62369111, 22.80358202, 15.16337821, 19.33356285,
       27.55096665, 31.83433948, 27.7494629 , 35.83424724, 16.26033588,
       17.68242469, 37.37614934, 16.41930026, 33.38213047, 12.46345181,
       28.60320968, 17.85716859, 29.50080738, 36.82727746, 18.12409313,
       34.55257242, 32.94541367, 11.28231178, 27.58780333, 21.71

In [23]:
df_acpred=pd.DataFrame({"actual":y_test,"predicted":p})

In [24]:
df_acpred

actual  predicted
305    28.4  31.357751
143    15.6  11.339498
8      16.5  10.730310
149    15.4  14.200325
435    13.4  12.995922
..      ...        ...
162    50.0  40.857574
178    29.9  31.778351
28     18.4  19.446373
361    19.9  18.879715
505    11.9  22.726695

[102 rows x 2 columns]

In [28]:
corr,_=pearsonr(y_test,p)

corr

0.87361857097969

In [27]:
corr**2

0.7632094075605956

In [29]:
model1.coef_

array([-1.08780890e-01,  5.43427050e-02,  2.97592492e-02,  2.53488011e+00,
       -2.02682475e+01,  3.57032887e+00,  5.81924734e-03, -1.62775549e+00,
        3.32647416e-01, -1.32164785e-02, -9.59764849e-01,  8.77734470e-03,
       -5.75943308e-01])

In [30]:
model1.intercept_

40.55399789404644

In [31]:
from statsmodels.formula.api import ols

In [32]:
model2=ols("medv~crim+zn+indus+chas+nox+rm+age+dis+rad+tax+ptratio+black+lstat",data=df_boston).fit()

In [33]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Sun, 28 Nov 2021   Prob (F-statistic):          6.72e-135
Time:                        07:30:50   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     36.4595      5.103      7.144      0.000      26.432      46.487
crim          -0.1080      0.033     -3.287      0.001      -0.173      -0.043
zn             0.0464      0.014      3.382      0.001       0.019       0.073
indus          0.0206      0.061      0.334      0.738      -0.100       0.141
chas           2.6867      0.862      3.118      0.002       0.994       4.380
nox          -17.7666      3.820     -4.651      0.000     -25.272     -10.262
rm             3.8099      0.418      9.116      0.000       2.989       4.631
age            0.0007      0.013      0.052      0.958      -0.025       0.027
dis           -1.4756      0.199     -7.398      0.000      -1.867      -1.084
rad            0.3060      0.066      4.613      0.000       0.176       0.436
tax           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
ptratio       -0.9527      0.131     -7.283      0.000      -1.210      -0.696
black          0.0093      0.003      3.467      0.001       0.004       0.015
lstat         -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""